import { z } from 'zod';
import { BillingDetailsSchema } from '@api-schemas/objects/billing-details.schema';
import { ChargeStatusEnum } from '@constants/enums';
import { ShippingSchema } from '@api-schemas/objects/shipping.schema';

export const ChargeResponseSchema = z.object({
  id: z.string(),
  object: z.literal('charge'),
  amount: z.number(),
  amount_captured: z.number(),
  amount_refunded: z.number(),
  application: z.string().nullable().optional(),
  application_fee: z.string().nullable().optional(),
  application_fee_amount: z.number().nullable().optional(),
  balance_transaction: z.string().nullable().optional(),
  billing_details: BillingDetailsSchema,
  calculated_statement_descriptor: z.string().nullable().optional(),
  captured: z.boolean(),
  created: z.number(),
  currency: z.string(),
  customer: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  disputed: z.boolean(),
  failure_balance_transaction: z.string().nullable().optional(),
  failure_code: z.string().nullable().optional(),
  failure_message: z.string().nullable().optional(),
  fraud_details: z.record(z.string(), z.any()).nullable().optional(),
  livemode: z.boolean(),
  metadata: z.record(z.string(), z.string()),
  on_behalf_of: z.string().nullable().optional(),
  outcome: z.record(z.string(), z.any()).nullable().optional(),
  paid: z.boolean(),
  payment_intent: z.string().nullable().optional(),
  payment_method: z.string().nullable().optional(),
  payment_method_details: z.record(z.string(), z.any()).nullable().optional(),
  presentment_details: z.record(z.string(), z.any()).nullable().optional(),
  radar_options: z.record(z.string(), z.any()).nullable().optional(),
  receipt_email: z.string().nullable().optional(),
  receipt_number: z.string().nullable().optional(),
  receipt_url: z.string().nullable().optional(),
  refunded: z.boolean(),
  refunds: z.record(z.string(), z.any()).nullable().optional(),
  review: z.string().nullable().optional(),
  shipping: ShippingSchema.nullable().optional(),
  source_transfer: z.string().nullable().optional(),
  statement_descriptor: z.string().nullable().optional(),
  statement_descriptor_suffix: z.string().nullable().optional(),
  status: z.enum(ChargeStatusEnum),
  transfer: z.string().nullable().optional(),
  transfer_data: z.record(z.string(), z.any()).nullable().optional(),
  transfer_group: z.string().nullable().optional(),
});

export type ChargeResponse = z.infer<typeof ChargeResponseSchema>;
